#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: $(basename $0) pkgbase"
  exit
else
  pkgbase="$1"
fi

preset="/etc/mkinitcpio.d/${pkgbase}.preset"
[ ! -f  "${preset}" ] && exit 1
source ${preset}
source ${default_config}
source "/etc/initcpio/hooks/${pkgbase}"

binaries=(bash mount umount ls cat
  lsmod rmmod insmod modinfo modprobe depmod
  switch_root readlink basename sync blkid
  cp dd mkdir mknod sed sleep ln rm uname touch chroot
  grep head tail cut
  )

for module in ${MODULES[*]}; do
  modfile=$(modinfo -k ${ALL_kver} -F filename ${module})
  [ -n "${modfile}" ] && modules+=("${modfile}")
done

wdir="/tmp/initramfs.$$"

function mkchroot
{
  [ $# -lt 2 ] && return
  dest=$1
  shift
  for i in "$@"; do
    [ "${i:0:1}" == "/" ] || i=$(which $i 2>/dev/null)
    [ -f "$dest/$i" ] && continue
    if [ -e "$i" ]; then
      d=`echo "$i" | grep -o '.*/'` &&
      mkdir -p "$dest/$d" &&
      cat "$i" > "$dest/$i" &&
      chmod +x "$dest/$i"
      mkchroot "$dest" $(ldd "$i" 2>/dev/null | grep -E -o '/.* ')
    elif [ -n "$i" ]; then
      echo "Possibly missing binary: $i"
    fi
  done
}

echo "Building ${default_image}..."

rm -rf $wdir

mkdir -p      $wdir/{dev,etc,proc,run,sys,usr/lib,usr/bin,usr/local,mnt/root,etc/modprobe.d}
ln -s usr/bin $wdir/bin
ln -s usr/bin $wdir/sbin
ln -s ../bin  $wdir/usr/local/bin
ln -s ../bin  $wdir/usr/local/sbin
ln -s bin     $wdir/usr/sbin
ln -s usr/lib $wdir/lib
ln -s usr/lib $wdir/lib64
ln -s lib     $wdir/usr/lib64
mknod -m 640  $wdir/dev/console c 5 1
mknod -m 664  $wdir/dev/null    c 1 3
mkchroot      $wdir ${binaries[*]} ${BINARIES[*]} ${FILES[*]} ${modules[*]}

if [[ "${MODULES_DECOMPRESS}" == "yes" ]]; then
  for modfile in ${modules[*]}; do
    zstd --rm -q -d "${wdir}${modfile}"
  done
fi

touch $wdir/etc/modprobe.d/modprobe.conf

echo -e -n '#!/bin/bash\n#' > "$wdir/init"
type run_hook >> "$wdir/init"
cat <<'EOT' | tee -a "$wdir/init" >/dev/null

PATH=/usr/bin
export PATH

mount -n -t devtmpfs devtmpfs /dev
mount -n -t proc     proc     /proc
mount -n -t sysfs    sysfs    /sys
mount -n -t tmpfs    tmpfs    /run

read -r cmdline < /proc/cmdline
init=/sbin/init
export root=
rootdelay=
rootfstype=auto
ro="ro"
rootflags=
device=
for param in $cmdline ; do
  case $param in
    init=*      ) init=${param#init=}             ;;
    root=*      ) export root=${param#root=}      ;;
    rootdelay=* ) rootdelay=${param#rootdelay=}   ;;
    rootfstype=*) rootfstype=${param#rootfstype=} ;;
    rootflags=* ) rootflags=${param#rootflags=}   ;;
    ro          ) ro="ro"                         ;;
    rw          ) ro="rw"                         ;;
  esac
done

run_hook

[ -n "$rootdelay" ] && sleep "$rootdelay"
mkdir /.root
[ -n "$rootflags" ] && rootflags+=","
rootflags+="$ro"
device="$root"
if [ -z "$device" ];then
  echo "No root device specified."
  bash
fi
for (( i = 0 ; i < 50 ; i++ )); do
  [[ "$root" =~ "=" ]] && device=$(blkid -t $root -l -o device)
  [ -b "$device" ] && break || sleep 0.1
done

if ! mount -n -t "$rootfstype" -o "$rootflags" "$device" /.root ; then
  echo "Device $device could not be mounted!"
  bash
else
  echo "Successfully mounted device $root"
fi

exec switch_root /.root "$init" "$@"
EOT
chmod +x $wdir/init

cat <<'EOT' | tee "$wdir/bin/reboot" >/dev/null
#!/bin/bash
/bin/sync
echo 1 > /proc/sys/kernel/sysrq
echo _sb > /proc/sysrq-trigger
EOT
chmod +x "$wdir/bin/reboot"

[ -z "${COMPRESSION}" ] && COMPRESSION="gzip"
( cd $wdir; find . -print0 | cpio --null -o --format=newc | zstd --format=${COMPRESSION} -19 -T0) > $default_image

rm -rf $wdir

stat --printf="Filesize: %s\n" $default_image

