#!/bin/bash

INITRAMFS_FILE="testimage"

[ -n "$1" ] && INITRAMFS_FILE="$1"
[ -n "$2" ] && kver="$2"

commands="bash parted lsblk mount umount ls cat ip bridge ethtool 
  lsmod rmmod insmod modinfo modprobe depmod
  switch_root readlink basename nano sync blkid
  cp dd mkdir mknod sed sleep ln rm uname touch chroot grep
  "

binfiles=""
binfiles="$binfiles "
binfiles="$binfiles "

firmwares="
	/lib/firmware/airoha/EthMD32.DSP.bin
	/lib/firmware/airoha/EthMD32.dm.bin
	"

wdir="/tmp/initramfs.$$"

function mkchroot
{
  [ $# -lt 2 ] && return
  dest=$1
  shift
  for i in "$@"
  do
    [ "${i:0:1}" == "/" ] || i=$(which $i 2>/dev/null)
    [ -f "$dest/$i" ] && continue
    if [ -e "$i" ]
    then
      d=`echo "$i" | grep -o '.*/'` &&
      mkdir -p "$dest/$d" &&
      cat "$i" > "$dest/$i" &&
      chmod +x "$dest/$i"
      mkchroot "$dest" $(ldd "$i" 2>/dev/null | grep -E -o '/.* ')
    fi
  done
}

rm -rf $wdir

mkdir -p      $wdir/{dev,etc,proc,run,sys,usr/lib,usr/bin,usr/local,mnt/root,etc/modprobe.d}
ln -s usr/bin $wdir/bin
ln -s usr/bin $wdir/sbin
ln -s ../bin  $wdir/usr/local/bin
ln -s ../bin  $wdir/usr/local/sbin
ln -s bin     $wdir/usr/sbin
ln -s usr/lib $wdir/lib
ln -s usr/lib $wdir/lib64
ln -s lib     $wdir/usr/lib64
mknod -m 640  $wdir/dev/console c 5 1
mknod -m 664  $wdir/dev/null    c 1 3
mkchroot      $wdir $commands $firmwares

touch $wdir/etc/modprobe.d/modprobe.conf

cat <<'EOT' | tee "$wdir/init" >/dev/null
#!/bin/bash
PATH=/usr/bin
export PATH

mount -n -t devtmpfs devtmpfs /dev
mount -n -t proc     proc     /proc
mount -n -t sysfs    sysfs    /sys
mount -n -t tmpfs    tmpfs    /run

read -r cmdline < /proc/cmdline
init=/sbin/init
root=
rootdelay=
rootfstype=auto
ro="ro"
rootflags=
device=
for param in $cmdline ; do
  case $param in
    init=*      ) init=${param#init=}             ;;
    root=*      ) root=${param#root=}             ;;
    rootdelay=* ) rootdelay=${param#rootdelay=}   ;;
    rootfstype=*) rootfstype=${param#rootfstype=} ;;
    rootflags=* ) rootflags=${param#rootflags=}   ;;
    ro          ) ro="ro"                         ;;
    rw          ) ro="rw"                         ;;
  esac
done

[ -n "$rootdelay" ] && sleep "$rootdelay"
mkdir /.root
[ -n "$rootflags" ] && rootflags+=","
rootflags+="$ro"
device="$root"
if [ -z "$device" ];then
  echo "No root device specified."
  bash
fi
for (( i = 0 ; i < 50 ; i++ )); do
  [[ "$root" =~ "=" ]] && device=$(blkid -t $root -l -o device)
  [ -b "$device" ] && break || sleep 0.1
done

if ! mount -n -t "$rootfstype" -o "$rootflags" "$device" /.root ; then
  echo "Device $device could not be mounted!"
  bash
else
  echo "Successfully mounted device $root"
fi

exec switch_root /.root "$init" "$@"
EOT
chmod +x $wdir/init

cat <<'EOT' | tee "$wdir/bin/reboot" >/dev/null
#!/bin/bash
/bin/sync
echo 1 > /proc/sys/kernel/sysrq
echo _sb > /proc/sysrq-trigger
EOT
chmod +x "$wdir/bin/reboot"

( cd $wdir; find . -print0 | cpio --null -o --format=newc | gzip -9) > $INITRAMFS_FILE

rm -rf $wdir

stat $INITRAMFS_FILE
