post_upgrade() {
  sudo systemctl --force --no-pager disable setmac.service
  echo
  sudo systemctl --force --no-pager enable setmac.service
  echo
  mkdir -p "/etc/systemd/networkd.conf.d"
  if [ ! -L "/etc/systemd/networkd.conf.d/networkd.conf" ]; then
    ln -srT ../network/networkd.conf /etc/systemd/networkd.conf.d/networkd.conf
  fi
}

post_install() {
  post_upgrade
}

pre_remove() {
  sudo systemctl --force --no-pager disable setmac.service
  rm -vf  /boot/dtbos/*-fixed.dtb
}
