dracutmodules+=" bash systemd systemd-ask-password systemd-initrd systemd-journald "
dracutmodules+=" systemd-modules-load systemd-sysctl systemd-tmpfiles systemd-udevd "
dracutmodules+=" systemd-sysusers btrfs "
dracutmodules+=" rootfs-block udev-rules dracut-systemd usrmount "
dracutmodules+=" base fs-lib shutdown "
dracutmodules+=" %PKGBASE% "

install_items+=" /lib/firmware/airoha/EthMD32.DSP.bin /lib/firmware/airoha/EthMD32.dm.bin "

