KERNEL_VERSION="NeedToChange"
PKGBASE="NeedToChange"

pre_upgrade() {
  export INITRD=Yes
  test -d /etc/kernel/preinst.d && run-parts --arg="${KERNEL_VERSION}" --arg="/boot/Image-${PKGBASE}" /etc/kernel/preinst.d
}

pre_install() {
  pre_upgrade "$@"
}

post_upgrade() {
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
  /usr/bin/bpir-toolbox --write2fip
  export INITRD=Yes
  test -d /etc/kernel/postinst.d && run-parts --arg="${KERNEL_VERSION}" --arg="/boot/Image-${PKGBASE}" /etc/kernel/postinst.d
}

post_install() {
  post_upgrade "$@"
}

post_remove() {
  rm -f /boot/initramfs-${PKGBASE}.img
  rm -f /boot/initramfs-${PKGBASE}-fallback.img
  export INITRD=Yes
  test -d /etc/kernel/postrm.d && run-parts --arg="${KERNEL_VERSION}" --arg="/boot/Image-${PKGBASE}" /etc/kernel/postrm.d
}

pre_remove() {
  export INITRD=Yes
  test -d /etc/kernel/prerm.d && run-parts --arg="${KERNEL_VERSION}" --arg="/boot/Image-${PKGBASE}" /etc/kernel/prerm.d
}
