# vim:set ft=sh
MODULES=()
BINARIES=(bash bpir-flash2emmc gzip gunzip mmc lsblk dtc)
FILES=()
case "$(blkid $(lsblk -pilno name,mountpoint|grep -G ' /$'|cut -d" " -f1) -s PARTLABEL -o value)" in
  bpir3m-*)
    FILES+=(/lib/firmware/airoha/EthMD32.dm.bin)
    FILES+=(/lib/firmware/airoha/EthMD32.DSP.bin)
    ;;
  bpir4l-*)
    FILES+=(/lib/firmware/mediatek/mt7987/i2p5ge-phy-DSPBitTb.bin)
    FILES+=(/lib/firmware/mediatek/mt7987/i2p5ge-phy-pmb.bin)
    ;;
  bpir4-*|bpir4p-*)
    FILES+=(/lib/firmware/mediatek/mt7988/i2p5ge-phy-pmb.bin)
    FILES+=(/lib/firmware/aeonsemi/as21x1x_fw.bin)
    ;;
esac
HOOKS=(base udev autodetect modconf block filesystems %PKGBASE%)
MODULES_DECOMPRESS="yes"
COMPRESSION=zstd
