# vim:set ft=sh
MODULES=()
BINARIES=(bpir-flash2emmc gzip gunzip mmc lsblk parted dtc)
BINARIES+=(partprobe wipefs)
BINARIES+=(fsck.f2fs fsck.btrfs fsck.vfat)
BINARIES+=(mkfs.f2fs mkfs.btrfs mkfs.vfat)
BINARIES+=(fdtget fdtput fdtoverlay ip bridge ethtool ping)
FILES=( /lib/firmware/airoha/EthMD32.dm.bin)
FILES+=(/lib/firmware/airoha/EthMD32.DSP.bin)
HOOKS=(base udev autodetect modconf block filesystems %PKGBASE%)
MODULES_DECOMPRESS="yes"
COMPRESSION=zstd

