# vim:set ft=sh
MODULES=()
BINARIES=(bpir-flash2emmc gzip gunzip mmc lsblk dtc)
FILES=( /lib/firmware/airoha/EthMD32.dm.bin)
FILES+=(/lib/firmware/airoha/EthMD32.DSP.bin)
HOOKS=(base udev autodetect modconf block filesystems %PKGBASE%)
MODULES_DECOMPRESS="yes"
COMPRESSION=zstd

