[Unit]
Before=ssh-fix-reboot.service
#BindsTo=sys-subsystem-net-devices-%i.device

[Service]
SyslogIdentifier=hostapd
Type=forking
PIDFile=/run/hostapd.%i.pid
Restart=on-failure
RestartSec=2
ExecStart=
ExecStart=/usr/bin/hostapd-launch --pidfile /run/hostapd.%i.pid --device %i
ExecReload=

