#!/bin/bash

unamer="${1}"
linuxpkg="${2#*Image-}"

echo -n "${linuxpkg}" >/lib/modules/${unamer}/pkgbase

echo ">>> Updating module dependencies for ${unamer}. Please wait ..."
depmod "${unamer}"

bpir-toolbox --write2dtb --write2fip --for-linux="${linuxpkg}"

exit 0
