#!/bin/bash

unamer="${1}"
if [[ "${2##*.}" == "itb" ]]; then
  linuxpkg="linux-image-${unamer}" # from altered mkdebian
  dumpimage -T flat_dt -o /boot/Image-${linuxpkg}.gz "${2}"
  (cd /boot; gunzip Image-${linuxpkg}.gz)
else
  linuxpkg="${2#*Image-}"
fi

dtbsdir="/usr/lib/${linuxpkg}"
[ ! -d "${dtbsdir}" ] && dtbsdir="/lib/modules/${unamer}/dtbs"
if [ -d "${dtbsdir}" ]; then
  mkdir -p "/boot/dtbs/${linuxpkg}"
  cp -vft  "/boot/dtbs/${linuxpkg}" "${dtbsdir}/"*"/"*
fi

echo -n "${linuxpkg}" >/lib/modules/${unamer}/pkgbase

echo ">>> Updating module dependencies for ${unamer}. Please wait ..."
depmod "${unamer}"

bpir-toolbox --write2dtb --write2fip --for-linux="${linuxpkg}"

exit 0
