#!/bin/bash

unamer="${1}"
if [[ "${2##*.}" == "itb" ]]; then
  linuxpkg="linux-image-${unamer}" # from altered mkdebian
else
  linuxpkg="${2#*Image-}"
fi

bpir-toolbox --remove-dtb --pkgbase="${linuxpkg}"

bpir-toolbox --clean-boot --pkgbase="${linuxpkg}"

rm -vf /lib/modules/${unamer}/pkgbase

exit 0
