post_upgrade() {
  sudo systemctl --force --no-pager disable ssh-fix-reboot.service
  echo
  sudo systemctl --force --no-pager enable ssh-fix-reboot.service
  echo
}

post_install() {
  sudo systemctl --force --no-pager disable ssh-fix-reboot.service
  echo
  sudo systemctl --force --no-pager enable ssh-fix-reboot.service
  echo
}

pre_remove() {
  sudo systemctl --force --no-pager disable ssh-fix-reboot.service
  echo
}
